## ----setup, warning = FALSE, include = FALSE----------------------------------
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  out.width = "auto",
  out.height = "480px",
  fig.width = 7,
  fig.height = 5,
  fig.align = "center",
  fig.retina = 1,
  dpi = 150
)

list.of.packages <- c("dplyr", "kableExtra", "geozoo", "plotly", "purrr", "sp",  "data.table", "gridExtra","plyr")
new.packages <-
  list.of.packages[!(list.of.packages %in% installed.packages()[, "Package"])]
if (length(new.packages))
  install.packages(new.packages, dependencies = TRUE, repos='https://cloud.r-project.org/')
lapply(list.of.packages, library, character.only = TRUE)

options(expressions = 10000)
global_var <- nzchar(Sys.getenv("RUN_VIGNETTE"))
global_var <- TRUE
scrolLimit <- function(noOfRows){
  if(noOfRows<10){
    swe = paste(as.character(noOfRows*50),"px")
  }
  else{
    swe = "400px"
  }
  return(swe)
}

Table <- function(data,scroll = FALSE, limit = NULL){
  if(!is.null(limit)){
    data <- head(data,limit)
  }
  kable_table <- data %>% kable(escape = FALSE,align = "c") %>% kable_styling(bootstrap_options = c("striped", "hover", "responsive"))
  scroll <- scroll
  if(scroll == TRUE){
  kable_table <- kable_table %>% scroll_box(width = "100%", height = scrolLimit(nrow(data)))
  }
 return(kable_table)
}

set.seed(240)

## ----Quantization Error,echo=FALSE,warning=FALSE,fig.show='hold',message=FALSE,fig.cap='Figure 1: The Voronoi tessellation for level 1 shown for the 5 cells with the points overlayed'----
knitr::include_graphics('quant_explainer.png')

## -----------------------------------------------------------------------------
###direct installation###
#install.packages("HVT")

#or

###git repo installation###
#library(devtools)
#devtools::install_github(repo = "Mu-Sigma/HVT")


## ---- loading all the script files of the package, message=FALSE, warning=FALSE, include = TRUE----
# Sourcing required code scripts for HVT
script_dir <- "../R"
r_files <- list.files(script_dir, pattern = "\\.R$", full.names = TRUE)
invisible(lapply(r_files, function(file) { source(file, echo = FALSE); }))

## ----torus generate,warning=FALSE,message=FALSE,eval = global_var-------------
set.seed(240)
# Here p represents dimension of object, n represents number of points
torus <- geozoo::torus(p = 3,n = 12000) 
torus_df <- data.frame(torus$points)
colnames(torus_df) <- c("x","y","z")
torus_df <- torus_df %>% round(4)
Table(head(torus_df))

## ----torus plot,warning=FALSE,message=FALSE,fig.show="hold",fig.cap='Figure 2: 3D Torus',eval =TRUE,echo=TRUE, fig.align='center'----
plot_ly(x = torus_df$x, y = torus_df$y, z = torus_df$z, type = 'scatter3d',mode = 'markers',
marker = list(color = torus_df$z,colorscale = c('red', 'blue'),showscale = TRUE,size = 3,colorbar = list(title = 'z'))) %>%
layout(scene = list(xaxis = list(title = 'x'),yaxis = list(title = 'y'),zaxis = list(title = 'z'),
aspectratio = list(x = 1, y = 1, z = 0.4)))
 

## ---- message=FALSE, warning=FALSE--------------------------------------------
str(torus_df)

## ---- warning=FALSE,message=FALSE---------------------------------------------
edaPlots(torus_df)

## ----train-test torus,warning=FALSE,message=FALSE,eval = global_var-----------
smp_size <- floor(0.80 * nrow(torus_df))
set.seed(279)
train_ind <- sample(seq_len(nrow(torus_df)), size = smp_size)
torus_train <- torus_df[train_ind, ]
torus_test <- torus_df[-train_ind, ]

## ----torus head, warning=FALSE, eval = global_var-----------------------------
rownames(torus_train) <- NULL
Table(head(torus_train))

## ----train torus structure, warning=FALSE, eval = global_var------------------
str(torus_train)

## ---- train distribution, warning=FALSE,message=FALSE-------------------------
edaPlots(torus_train)

## ----torus 2 head, warning=FALSE, eval = global_var---------------------------
rownames(torus_test) <- NULL
Table(head(torus_test))

## ----torus test structure, warning=FALSE, eval = global_var-------------------
str(torus_test)

## ----torus test summary, warning=FALSE,message=FALSE--------------------------
edaPlots(torus_test)

## ----trainHVT function, echo = TRUE, eval= FALSE------------------------------
#  trainHVT(
#    dataset,
#    min_compression_perc,
#    n_cells,
#    depth,
#    quant.err,
#    projection.scale,
#    normalize = TRUE,
#    seed = 279,
#    distance_metric = c("L1_Norm", "L2_Norm"),
#    error_metric = c("mean", "max"),
#    quant_method = c("kmeans", "kmedoids"),
#    scale_summary = NA,
#    diagnose = FALSE,
#    hvt_validation = FALSE,
#    train_validation_split_ratio = 0.8
#  )

## ----trainhvt list,echo=FALSE,warning=FALSE,fig.show='hold',message=FALSE,fig.cap='Figure 3: The Output list generated by trainHVT function.', out.width="50%", out.height=  "20%", fig.align='center'----
knitr::include_graphics('hvt_results_list.png')

## ----torus hvt first,warning=FALSE,fig.show='hold',results='hide',message=FALSE,eval = global_var----
set.seed(240)
hvt.torus <- trainHVT(
  torus_train,
  n_cells = 100,
  depth = 1,
  quant.err = 0.1,
  normalize = FALSE,
  distance_metric = "L1_Norm",
  error_metric = "max",
  quant_method = "kmeans"
)


## ----compression summary torus first,warning=FALSE,eval = global_var----------
displayTable(data = hvt.torus[[3]]$compression_summary,columnName = 'percentOfCellsBelowQuantizationErrorThreshold', value = 0.8, tableType = "compression")

## ---- warning=FALSE,message=FALSE,fig.cap='Figure 4: Sammons 1D x Cell ID plot for layer 1 shown for the 100 cells in the torus training dataset'----
plotHVT(hvt.torus, plot.type = '1D')

## ----torus hvt second,warning=FALSE,fig.show='hold',results='hide',message=FALSE,eval = global_var----
set.seed(240)
hvt.torus2 <- trainHVT(
  torus_train,
  n_cells = 300,
  depth = 1,
  quant.err = 0.1,
  normalize = FALSE,
  distance_metric = "L1_Norm",
  error_metric = "max",
  quant_method = "kmeans"
)


## ----compression summary torus second,warning=FALSE,eval = global_var---------
displayTable(data = hvt.torus2[[3]]$compression_summary,columnName = 'percentOfCellsBelowQuantizationErrorThreshold', value = 0.8, tableType = "compression")


## ---- warning=FALSE,message=FALSE,fig.cap='Figure 5: Sammons 1D x Cell ID plot for layer 1 shown for the 300 cells in the torus training dataset',out.width="100%", out.height="60%"----
plotHVT(hvt.torus2, plot.type = '1D')

## ----torus hvt third ,warning=FALSE,fig.show='hold',results='hide',message=FALSE,eval = global_var----
set.seed(240)
hvt.torus3 <- trainHVT(
  torus_train,
  n_cells = 900,
  depth = 1,
  quant.err = 0.1,
  normalize = FALSE,
  distance_metric = "L1_Norm",
  error_metric = "max",
  quant_method = "kmeans"
)


## ----compression summary torus third,warning=FALSE,eval = global_var----------
displayTable(data = hvt.torus3[[3]]$compression_summary,columnName = 'percentOfCellsBelowQuantizationErrorThreshold', value = 0.8, tableType = "compression")


## ---- warning=FALSE,message=FALSE,fig.cap='Figure 6: Sammons 1D x Cell ID plot for layer 1 shown for the 900 cells in the torus training dataset',out.width="100%", out.height="60%"----
plotHVT(hvt.torus3, plot.type = '1D')

## ----plotHVT function,echo = TRUE, eval= FALSE--------------------------------
#  plotHVT <-(hvt.results, line.width, color.vec,pch1 = 21, centroid.size = 1.5,
#          title = NULL, maxDepth = NULL, child.level,hmap.cols,
#          quant.error.hmap = NULL, n_cells.hmap = NULL,
#          label.size = 0.5, sepration_width = 7,layer_opacity = c(0.5, 0.75, 0.99),
#          dim_size = 1000, plot.type = '2Dhvt')

## ---- warning=FALSE,message=FALSE, fig.cap='Figure 7: Sammons 2D Plot for 100 cells'----
plotHVT(hvt.torus, plot.type = '2Dproj')

## ---- message=FALSE,warning=FALSE,fig.cap='Figure 8: Sammons 2D Plot for 300 cells'----
plotHVT(hvt.torus2, plot.type = '2Dproj')

## ---- warning=FALSE,message=FALSE,fig.cap='Figure 9: Sammons 2D Plot for 900 cells'----
plotHVT(hvt.torus3, plot.type = '2Dproj')

## ---- warning=FALSE,message=FALSE,fig.cap='Figure 10: The Voronoi tessellation for layer 1 shown for the 100 cells in the torus training dataset'----
plotHVT(
  hvt.torus,
  line.width = c(0.4),
  color.vec = c("navy blue"),
  centroid.size = 0.6,
  maxDepth = 1, 
  plot.type = '2Dhvt'
)

## ---- warning=FALSE,message=FALSE,fig.cap='Figure 11: The Voronoi tessellation for layer 1 shown for the 300 cells in the torus training dataset'----
plotHVT(
  hvt.torus2,
  line.width = c(0.4),
  color.vec = c("navy blue"),
  centroid.size = 0.6,
  maxDepth = 1,
  plot.type = '2Dhvt'
)

## ---- warning=FALSE,message=FALSE,fig.cap='Figure 12: The Voronoi tessellation for layer 1 shown for the 900 cells in the torus training dataset'----
plotHVT(
  hvt.torus3,
  line.width = c(0.4),
  color.vec = c("navy blue"),
  centroid.size = 0.6,
  maxDepth = 1,
  plot.type = '2Dhvt'
)

## ----hmp level two quantization torus n demo,warning=FALSE,fig.show='hold',results='hide',message=FALSE,fig.cap='Figure 13: The Voronoi tessellation for layer 1 and number of cells 900 with the heat map overlaid for `No. of entities in each cell` in the torus dataset',eval = global_var----
plotHVT(
  hvt.torus3,
  child.level = 1,
  hmap.cols = "n",
  line.width = c(0.4),
  color.vec = c("navy blue"),
  centroid.size = 0.8,
  plot.type = '2Dheatmap'
)

## ----hmp level two quantization torus x demo,warning=FALSE,fig.show='hold',results='hide',message=FALSE,fig.cap='Figure 14: The Voronoi tessellation for layer 1 and number of cells 900 with the heat map overlaid for variable `x` in the torus dataset',eval = global_var----
plotHVT(
  hvt.torus3,
  child.level = 1,
  hmap.cols = "x",
  line.width = c(0.4),
  color.vec = c("navy blue"),
  centroid.size = 0.8,
  plot.type = '2Dheatmap'
)

## ----hmp level two quantization torus y demo,warning=FALSE,fig.show='hold',results='hide',message=FALSE,fig.cap='Figure 15: The Voronoi tessellation for layer 1 and number of cells 900 with the heat map overlaid for variable `y` in the torus dataset',eval = global_var----
plotHVT(
  hvt.torus3,
  child.level = 1,
  hmap.cols = "y",
  line.width = c(0.4),
  color.vec = c("navy blue"),
  centroid.size = 0.8,
  plot.type = '2Dheatmap'
)

## ----hmp level two quantization torus z demo,warning=FALSE,fig.show='hold',results='hide',message=FALSE,fig.cap='Figure 16: The Voronoi tessellation for layer 1 and number of cells 900 with the heat map overlaid for variable `z` in the torus dataset',eval = global_var----
plotHVT(
  hvt.torus3,
  child.level = 1,
  hmap.cols = "z",
  line.width = c(0.4),
  color.vec = c("navy blue"),
  centroid.size = 0.8,
  plot.type = '2Dheatmap'
)

## ----scoreHVT function1,echo = TRUE, eval= FALSE------------------------------
#  scoreHVT(data,
#           hvt.results.model,
#           child.level,
#           mad.threshold,
#           line.width,
#           color.vec,
#           normalize,
#           seed,
#           distance_metric,
#           error_metric,
#           yVar)

## ----scoreHVT torus,warning=FALSE,message=FALSE,eval = global_var-------------
set.seed(240)
scoring_torus <- scoreHVT(
  torus_test,
  hvt.torus3,
  child.level = 1,
  line.width = c(1.2),
  color.vec = c("navy blue"),
  normalize = FALSE
)

## -----------------------------------------------------------------------------
Act_pred_Table <- scoring_torus[["actual_predictedTable"]]
rownames(Act_pred_Table) <- NULL
Act_pred_Table %>% head(100) %>%as.data.frame() %>%Table(scroll = TRUE, limit = 100)

## ---- warning=FALSE,message=FALSE,fig.cap='Figure 17: Mean Absolute Difference'----
hist(Act_pred_Table$diff, breaks = 20, col = "blue", main = "Mean Absolute Difference", xlab = "Difference",xlim = c(0,0.20), ylim = c(0,500))



## ----load data computer,warning=FALSE,message=FALSE,eval = TRUE---------------
set.seed(240)
computers <- read.csv("https://raw.githubusercontent.com/Mu-Sigma/HVT/master/vignettes/sample_dataset/Computers.csv")

## ----sample data computer,warning=FALSE,message=FALSE,eval = TRUE-------------
computers <- computers[,-1]
Table(head(computers))

## ----data structure computer,warning=FALSE,message=FALSE,eval = global_var----
str(computers)

## -----------------------------------------------------------------------------
computers <-computers %>% dplyr::select(-c( cd, multi, premium, trend))

## ---- computers dataset distribution, warning=FALSE,message=FALSE-------------
edaPlots(computers)

## ----train-test computer,warning=FALSE,message=FALSE,eval = global_var--------
num_rows <- nrow(computers)
set.seed(123)
train_indices <- sample(1:num_rows, 0.8 * num_rows)
trainComputers <- computers[train_indices, ]
testComputers <- computers[-train_indices, ]

## ---- warning=FALSE,message=FALSE---------------------------------------------
trainComputers_data <- trainComputers %>% as.data.frame() %>% round(4)
trainComputers_data <- trainComputers_data %>% dplyr::select(price,speed,hd,ram,screen,ads)
row.names(trainComputers_data) <- NULL
Table(head(trainComputers_data))

## ----train computers structure, warning=FALSE, eval = global_var--------------
str(trainComputers_data)

## ---- warning=FALSE,message=FALSE---------------------------------------------
edaPlots(trainComputers_data)

## ----warning=FALSE,message=FALSE----------------------------------------------
testComputers_data <- testComputers %>% as.data.frame() %>% round(4)
testComputers_data <- testComputers_data %>% dplyr::select(price,speed,hd,ram,screen,ads)
rownames(testComputers_data) <- NULL
Table(head(testComputers_data))

## ----computers structure, warning=FALSE, eval = global_var--------------------
str(testComputers_data)

## ---- warning=FALSE,message=FALSE---------------------------------------------
edaPlots(testComputers_data)

## ----level one computers,warning=FALSE,message=FALSE,results='asis',eval = global_var----
set.seed(240)
hvt.results <- list()
hvt.results <- trainHVT(trainComputers,   
                          n_cells = 440,
                          depth = 1,
                          quant.err = 0.2,
                          normalize = TRUE,
                          distance_metric = "L1_Norm",
                          error_metric = "max",
                          quant_method = "kmeans")


## ----compression summary level one computers,warning=FALSE,eval = global_var----
displayTable(data = hvt.results[[3]]$compression_summary,columnName = 'percentOfCellsBelowQuantizationErrorThreshold', value = 0.8, tableType = "compression")


## ----summary level one computers,warning=FALSE,eval = global_var--------------
displayTable(data =hvt.results[[3]][['summary']], columnName= 'Quant.Error', value = 0.2, tableType = "summary")


## ---- warning=FALSE,message=FALSE,fig.cap='Figure 18: Sammons 1D x Cell ID plot for layer 1 shown for the 440 cells in the dataset ’computers’',out.width="100%", out.height="60%"----
plotHVT(hvt.results, plot.type = '1D')

## ---- warning=FALSE,message=FALSE,fig.cap='Figure 19: Sammons 2D Plot for 440 cells'----
plotHVT(hvt.results, plot.type = '2Dproj')

## ----plot level one computers,warning=FALSE,fig.show='hold',results='hide',message=FALSE,fig.cap='Figure 20: The Voronoi Tessellation for layer 1 shown for the 440 cells in the dataset ’computers’',eval = global_var----
plotHVT(hvt.results,
        line.width = c(0.2), 
        color.vec = c("navy blue"),
        centroid.size = 0.01,  
        maxDepth = 1,
        plot.type = '2Dhvt')



## ----hmp level one n computers,warning=FALSE,fig.show='hold',results='hide',message=FALSE,fig.cap='Figure 21: The Voronoi Tessellation with the heat map overlaid over the `No. of entities in each cell` in the ’computers’ dataset',eval = global_var----
plotHVT(
  hvt.results,
  child.level = 1,
  hmap.cols = "n",
  line.width = c(0.2),
  color.vec = c("navy blue"),
  centroid.size = 0.03,
  plot.type = '2Dheatmap'
)

## ----hmp level one price computers,warning=FALSE,fig.show='hold',results='hide',message=FALSE,fig.cap='Figure 22: The Voronoi Tessellation with the heat map overlaid over the variable `price` in the ’computers’ dataset',eval = global_var----

plotHVT(
  hvt.results,
  child.level = 1,
  hmap.cols = "price",
  line.width = c(0.2),
  color.vec = c("navy blue"),
  centroid.size = 0.03,
  plot.type = '2Dheatmap'
)

## ----hmp level one hd computers,warning=FALSE,fig.show='hold',results='hide',message=FALSE,fig.cap='Figure 23: The Voronoi Tessellation with the heat map overlaid over the variable `hd` in the ’computers’ dataset',eval = global_var----

plotHVT(
  hvt.results,
  child.level = 1,
  hmap.cols = "hd",
  line.width = c(0.2),
  color.vec = c("navy blue"),
  centroid.size = 0.03,
  plot.type = '2Dheatmap'
)


## ----hmp level one ram computers,warning=FALSE,fig.show='hold',results='hide',message=FALSE,fig.cap='Figure 24: The Voronoi Tessellation with the heat map overlaid over the variable `ram` in the ’computers’ dataset',eval = global_var----
plotHVT(
  hvt.results,
  child.level = 1,
  hmap.cols = "ram",
  line.width = c(0.2),
  color.vec = c("navy blue"),
  centroid.size = 0.03,
  plot.type = '2Dheatmap'
)

## ----hmp level one screen computers,warning=FALSE,fig.show='hold',results='hide',message=FALSE,fig.cap='Figure 25: The Voronoi Tessellation with the heat map overlaid over the variable `screen` in the ’computers’ dataset',eval = global_var----
plotHVT(
  hvt.results,
  child.level = 1,
  hmap.cols = "screen",
  line.width = c(0.2),
  color.vec = c("navy blue"),
  centroid.size = 0.03,
  plot.type = '2Dheatmap'
)


## ----hmp level one ads computers,warning=FALSE,fig.show='hold',results='hide',message=FALSE,fig.cap='Figure 26: The Voronoi Tessellation with the heat map overlaid over the variable `ads` in the ’computers’ dataset',eval = global_var----

plotHVT(
  hvt.results,
  child.level = 1,
  hmap.cols = "ads",
  line.width = c(0.2),
  color.vec = c("navy blue"),
  centroid.size = 0.03,
  plot.type = '2Dheatmap'
)


## ----scoreHVT function,echo = TRUE, eval= FALSE-------------------------------
#  scoreHVT(data,
#           hvt.results.model,
#           child.level,
#           mad.threshold,
#           line.width,
#           color.vec,
#           normalize,
#           seed,
#           distance_metric,
#           error_metric,
#           yVar)

## ----scoreHVT hmap computers,warning=FALSE,message=FALSE,eval = global_var----
set.seed(240)
scoring_comp <-scoreHVT(
  testComputers,
  hvt.results,
  child.level = 1,
  line.width = c(1.2),
  color.vec = c("navy blue"),
  normalize = TRUE
)

## -----------------------------------------------------------------------------
Act_pred_Table <- scoring_comp[["actual_predictedTable"]]
rownames(Act_pred_Table) <- NULL
Act_pred_Table %>% head(100) %>%as.data.frame() %>%Table(scroll = TRUE, limit = 100)

## ----message=FALSE,warning=FALSE,fig.cap='Figure 27: Mean Absolute Difference'----
hist(Act_pred_Table$diff, breaks = 20, col = "blue", main = "Mean Absolute Difference", xlab = "Difference",xlim = c(0,0.6), ylim = c(0,250))

