## ----setup, warning = FALSE, include = FALSE----------------------------------
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  out.width = "auto",
  out.height = "480px",
  fig.width = 7,
  fig.height = 5,
  fig.align = "center",
  fig.retina = 1,
  dpi = 150
)
list.of.packages <- c("plyr", "dplyr", "reactable", "kableExtra", "geozoo", "plotly", "purrr", "sp", "data.table", "gridExtra", "tidyr")
new.packages <-
  list.of.packages[!(list.of.packages %in% installed.packages()[, "Package"])]
if (length(new.packages))
  install.packages(new.packages, dependencies = TRUE, repos='https://cloud.r-project.org/')
lapply(list.of.packages, library, character.only = TRUE)



options(expressions = 10000)
global_var <- nzchar(Sys.getenv("RUN_VIGNETTE"))
global_var <- TRUE

scrolLimit <- function(noOfRows){
  if(noOfRows<10){
    swe = paste(as.character(noOfRows*50),"px")
  }
  else{
    swe = "400px"
  }
  return(swe)
}

Table <- function(data,scroll = TRUE, limit = NULL){
  if(!is.null(limit)){
    data <- head(data,limit)
  }
  kable_table <- data %>% kable(escape = FALSE,align = "c") %>% kable_styling(bootstrap_options = c("striped", "hover", "responsive"))
  scroll <- scroll
  
  if(scroll == TRUE){
  kable_table <- kable_table %>% scroll_box(width = "100%", height = scrolLimit(nrow(data)))
  }
  return(kable_table)
}

set.seed(240)

## -----------------------------------------------------------------------------
###direct installation###
#install.packages("HVT")

#or

###git repo installation###
#library(devtools)
#devtools::install_github(repo = "Mu-Sigma/HVT")


## ---- loading all the script files of the package, message=FALSE, warning=FALSE, include = TRUE----
# Sourcing required code scripts for HVT
script_dir <- "../R"
r_files <- list.files(script_dir, pattern = "\\.R$", full.names = TRUE)
invisible(lapply(r_files, function(file) { source(file, echo = FALSE); }))

## ----torus generate,warning=FALSE,message=FALSE,eval = global_var-------------
set.seed(240)
# Here p represents dimension of object, n represents number of points
torus <- geozoo::torus(p = 3,n = 12000)
torus_df <- data.frame(torus$points)
colnames(torus_df) <- c("x","y","z")
torus_df <- torus_df %>% round(4)
Table(head(torus_df), scroll = FALSE)

## ---- message=FALSE, warning=FALSE--------------------------------------------
str(torus_df)

## ---- warning=FALSE, message=FALSE--------------------------------------------
edaPlots(torus_df)

## ----train-test torus,warning=FALSE,message=FALSE,eval = global_var-----------
smp_size <- floor(0.80 * nrow(torus_df))
set.seed(279)
train_ind <- sample(seq_len(nrow(torus_df)), size = smp_size)
torus_train <- torus_df[train_ind, ]
torus_test <- torus_df[-train_ind, ]

## ----torus head, warning=FALSE, eval = global_var-----------------------------
rownames(torus_train) <- NULL
Table(head(torus_train), scroll= FALSE)

## ----train torus structure, warning=FALSE, eval = global_var------------------
str(torus_train)

## ---- warning=FALSE,message=FALSE---------------------------------------------
edaPlots(torus_train)

## ----torus 2 head, warning=FALSE, eval = global_var---------------------------
rownames(torus_test) <- NULL
Table(head(torus_test), scroll = FALSE)

## ----torus test structure, warning=FALSE, eval = global_var-------------------
str(torus_test)

## ---- warning=FALSE,message=FALSE---------------------------------------------
edaPlots(torus_test)

## ----echo=FALSE,warning=FALSE,fig.show='hold',message=FALSE,fig.cap='Figure 1: Data Segregation with highlighted bounding box in red around compressed map A'----
knitr::include_graphics('scoreLayeredHVT_function_mapA.png')

## ----trainHVT function, echo=TRUE, eval=FALSE---------------------------------
#  trainHVT(
#    dataset,
#    min_compression_perc,
#    n_cells,
#    depth,
#    quant.err,
#    distance_metric = c("L1_Norm", "L2_Norm"),
#    error_metric = c("mean", "max"),
#    quant_method = c("kmeans", "kmedoids"),
#    normalize = TRUE,
#    seed = 279,
#    diagnose = FALSE,
#    hvt_validation = FALSE,
#    train_validation_split_ratio = 0.8
#  )

## ----trainhvt list,echo=FALSE,warning=FALSE,fig.show='hold',message=FALSE,fig.cap='Figure 2: The Output list generated by trainHVT function.', out.width="50%", out.height=  "20%", fig.align='center'----
knitr::include_graphics('hvt_results_list_score.png')

## ----torus hvt third ,warning=FALSE,fig.show='hold',results='hide',message=FALSE,fig.cap='Figure 5: The Voronoi tessellation for layer 1 shown for the 900 cells in the dataset ’torus’',eval = global_var----
set.seed(240)
torus_mapA <- trainHVT(
  torus_train,
  n_cells = 900,
  depth = 1,
  quant.err = 0.1,
  normalize = FALSE,
  distance_metric = "L1_Norm",
  error_metric = "max",
  quant_method = "kmeans"
)


## ----compression summary torus third,warning=FALSE,eval = global_var----------
displayTable(data = torus_mapA[[3]]$compression_summary,columnName = 'percentOfCellsBelowQuantizationErrorThreshold', value = 0.8, tableType = "compression")

## ----hvt_mapA display results, warning=FALSE, echo=TRUE-----------------------
displayTable(data =torus_mapA[[3]][['summary']], columnName= 'Quant.Error', value = 0.1, tableType = "summary")


## ----plotHVT function,echo = TRUE, eval= FALSE--------------------------------
#  plotHVT <-(hvt.results, line.width, color.vec, pch1 = 21, centroid.size = 1.5,
#             title = NULL, maxDepth = NULL, child.level, hmap.cols,
#             quant.error.hmap = NULL, n_cells.hmap = NULL, label.size = 0.5,
#             sepration_width = 7, layer_opacity = c(0.5, 0.75, 0.99), dim_size = 1000, plot.type = '2Dhvt')

## ---- warning=FALSE,message=FALSE,fig.cap='Figure 3: The Voronoi Tessellation for layer 1 (map A) shown for the 900 cells in the dataset ’torus’'----
plotHVT(torus_mapA,
        line.width = c(0.4), 
        color.vec = c("navy blue"),
        centroid.size = 0.01,
        maxDepth = 1,
        plot.type = "2Dhvt") 

## ----hvt_mapA hmp level x torus,warning=FALSE,fig.show='hold',results='hide',message=FALSE,fig.cap='Figure 4: The Voronoi Tessellation with the heat map overlaid for variable ’x’ in the ’torus’ dataset',eval = global_var----

  plotHVT(
  torus_mapA,
  child.level = 1,
  hmap.cols = "x",
  line.width = c(0.2),
  color.vec = c("navy blue"),
  centroid.size = 0.1,
  plot.type = '2Dheatmap'
) 


## ----hvt_mapA hmp level y torus,warning=FALSE,fig.show='hold',results='hide',message=FALSE,fig.cap='Figure 5: The Voronoi Tessellation with the heat map overlaid for variable ’y’ in the ’torus’ dataset',eval = global_var----

  plotHVT(
  torus_mapA,
  child.level = 1,
  hmap.cols = "y",
  line.width = c(0.2),
  color.vec = c("navy blue"),
  centroid.size = 0.1,
  plot.type = '2Dheatmap'
) 


## ----hvt_mapA hmp  level one z torus,warning=FALSE,fig.show='hold',results='hide',message=FALSE,fig.cap='Figure 6: The Voronoi Tessellation with the heat map overlaid for variable ’z’ in the ’torus’ dataset',eval = global_var----

  plotHVT(
  torus_mapA,
  child.level = 1,
  hmap.cols = "z",
  line.width = c(0.2),
  color.vec = c("navy blue"),
  centroid.size = 0.1,
  plot.type = '2Dheatmap'
) 


## ----echo=FALSE,warning=FALSE,fig.show='hold',message=FALSE,fig.cap='Figure 7: Data Segregation with highlighted bounding box in red around map B'----
knitr::include_graphics('scoreLayeredHVT_function_mapB.png')

## ----echo=FALSE,warning=FALSE,fig.show='hold',message=FALSE,fig.cap='Figure 8: Manually selecting novelty cells'----
knitr::include_graphics('reference.png')

## ----remove_novelty,results='asis', message=FALSE-----------------------------
identified_Novelty_cells <<- c(595,425,165,875,822,697,166)   #as a example
output_list <- removeNovelty(identified_Novelty_cells, torus_mapA)
data_with_novelty <- output_list[[1]]
data_without_novelty <- output_list[[2]]

## ----hvt_mapB results, warning=FALSE, echo=TRUE-------------------------------
novelty_data <- data_with_novelty
novelty_data$Row.No <- row.names(novelty_data)
novelty_data <- novelty_data %>% dplyr::select("Row.No","Cell.ID","Cell.Number","x","y","z")
colnames(novelty_data) <- c("Row.No","Cell.ID","Segment.Child","x","y","z")
Table(novelty_data,scroll = TRUE, limit = 100)

## ----compress_novelty_plot,warning=FALSE,fig.show='hold',results='hide',message=FALSE,fig.cap='Figure 9: The Voronoi Tessellation constructed using the compressed HVT map (map A) with the novelty cell(s) highlighted in red',eval = global_var----
plotNovelCells(identified_Novelty_cells, torus_mapA,line.width = c(0.4),centroid.size = 0.01)

## ---- message=FALSE,warning=FALSE---------------------------------------------
colnames(data_with_novelty) <- c("Cell.ID","Segment.Child","x","y","z")
data_with_novelty <- data_with_novelty[,-1:-2]
torus_mapB <- list()
mapA_scale_summary = torus_mapA[[3]]$scale_summary
torus_mapB <- trainHVT(data_with_novelty,
                  n_cells = 11,   
                  depth = 1,
                  quant.err = 0.1,
                  normalize = FALSE,
                  distance_metric = "L1_Norm",
                  error_metric = "max",
                  quant_method = "kmeans"
                  )


## ---- message=FALSE,warning=FALSE---------------------------------------------
displayTable(data =torus_mapB[[3]][['summary']], columnName= 'Quant.Error', value = 0.1, tableType = "summary")

## ----hvt_map_B compression summary,warning=FALSE,eval = global_var------------
displayTable(data = torus_mapB[[3]]$compression_summary,columnName = 'percentOfCellsBelowQuantizationErrorThreshold', value = 0.8, tableType = "compression")

## ----echo=FALSE,warning=FALSE,fig.show='hold',message=FALSE,fig.cap='Figure 10:Data Segregation with highlighted bounding box in red around compressed map C'----
knitr::include_graphics('scoreLayeredHVT_function_mapC.png')

## ----warning=FALSE,message=FALSE----------------------------------------------
torus_mapC <- list()
torus_mapC <- trainHVT(data_without_novelty,
                  n_cells = 10,
                  depth = 2,
                  quant.err = 0.1,
                  normalize = FALSE,
                  distance_metric = "L1_Norm",
                  error_metric = "max",
                  quant_method = "kmeans")

## ----hvt_map_C compression summary,warning=FALSE,eval = global_var------------
displayTable(data = torus_mapC[[3]]$compression_summary,columnName = 'percentOfCellsBelowQuantizationErrorThreshold', value = 0.8, tableType = "compression")


## ----warning=FALSE,message=FALSE----------------------------------------------
torus_mapC <- list()
torus_mapC <- trainHVT(data_without_novelty,
                  n_cells = 30,    
                  depth = 2,
                  quant.err = 0.1,
                  normalize = FALSE,
                  distance_metric = "L1_Norm",
                  error_metric = "max",
                  quant_method = "kmeans")

## ----message=FALSE,warning=FALSE----------------------------------------------
displayTable(data =torus_mapC[[3]][['summary']], columnName= 'Quant.Error', value = 0.1, tableType = "summary")

## ----hvt_mapC compression summary,warning=FALSE,eval = global_var-------------
displayTable(data = torus_mapC[[3]]$compression_summary,columnName = 'percentOfCellsBelowQuantizationErrorThreshold', value = 0.8, tableType = "compression")

## ---- warning=FALSE,message=FALSE,fig.cap='Figure 11: The Voronoi Tessellation for layer 2 (map C) shown for the 928 cells in the dataset ’torus’ at level 2'----
plotHVT(torus_mapC,
        line.width = c(0.2,0.1), 
        color.vec = c("navyblue","steelblue"),
        centroid.size = 0.1,
        maxDepth = 2, 
        plot.type = '2Dhvt')
 

## ----hvt_mapC hmp level one x torus,warning=FALSE,fig.show='hold',results='hide',message=FALSE,fig.cap='Figure 12: The Voronoi Tessellation with the heat map overlaid for feature `x` in the ’torus’ dataset' , eval = global_var----
  plotHVT(
  torus_mapC,
  child.level = 2,
  hmap.cols = "x",
  line.width = c(0.2,0.1),
  color.vec = c("navyblue","steelblue"),
  centroid.size = 0.1,
  plot.type = '2Dheatmap'
) 


## ----hvt_mapC hmp levelonetorus,warning=FALSE,fig.show='hold',results='hide',message=FALSE,fig.cap='Figure 13: The Voronoi Tessellation with the heat map overlaid for feature `y` in the ’torus’ dataset',eval = global_var----

  plotHVT(
  torus_mapC,
  child.level = 2,
  hmap.cols = "y",
  line.width = c(0.2,0.1),
  color.vec = c("navyblue","steelblue"),
  centroid.size = 0.1,
  plot.type = '2Dheatmap'
) 


## ----hvt_mapC hmp level one z torus,warning=FALSE,fig.show='hold',results='hide',message=FALSE,fig.cap='Figure 14: The Voronoi Tessellation with the heat map overlaid for feature `z` in the ’torus’ dataset',eval = global_var----

  plotHVT(
  torus_mapC,
  child.level = 2,
  hmap.cols = "z",
  line.width = c(0.2,0.1),
  color.vec = c("navyblue","steelblue"),
  centroid.size = 0.1,
  plot.type = '2Dheatmap'
) 


## ----scoreLayeredHVT function,echo = TRUE, eval= FALSE------------------------
#  scoreLayeredHVT(data,
#                  hvt_mapA,
#                  hvt_mapB,
#                  hvt_mapC,
#                  child.level = 1,
#                  mad.threshold = 0.2,
#                  normalize = TRUE,
#                  seed=300,
#                  distance_metric="L1_Norm",
#                  error_metric="max",
#                  yVar= NULL)

## ---- message=FALSE,warning=FALSE---------------------------------------------
validation_data <- torus_test
new_score <- scoreLayeredHVT(
    data=validation_data,
    hvt_mapA = torus_mapA,
    hvt_mapB = torus_mapB,
    hvt_mapC = torus_mapC,
    normalize = FALSE
  )

## -----------------------------------------------------------------------------
act_pred <- new_score[["actual_predictedTable"]]
rownames(act_pred) <- NULL
act_pred %>% head(100) %>%as.data.frame() %>%Table(scroll = TRUE)

## ----message=FALSE,warning=FALSE,fig.cap='Figure 16: Mean Absolute Difference'----
hist(act_pred$diff, breaks = 30, col = "blue", main = "Mean Absolute Difference", xlab = "Difference")

